services:
  dev:
    image: k_ueno-sphinx
    container_name: homepage
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    working_dir: /docs
    command: sphinx-autobuild . docs --host 0.0.0.0 --port 8000
